name: ci-examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    
    - name: Restore dependencies
      run: dotnet restore ef-examples/source/ef-examples.csproj
      
    - name: Build
      run: dotnet build ef-examples/source/ef-examples.csproj --no-restore
      
    - name: Test
      run: dotnet test ef-examples/source/ef-examples.csproj --no-build --verbosity normal
      
    - name: Qodana - Code Inspection
      uses: JetBrains/qodana-action@v2.0-eap
      with: 
        project-dir: ${{ github.workspace }}
        results-dir: ${{ github.workspace }}/qodana-results
        cache-dir: /home/runner/work/_temp/_github_home/qodana-cache
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/qodana
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: 'artifact'
        path: qodana
    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./qodana/report
        destination_dir: ./
