name: ci-examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    
    - name: Restore dependencies
      run: dotnet restore ef-examples.csproj
      
    - name: Build
      run: dotnet build /ef-examples/source/ef-examples.csproj --no-restore
      
    - name: Test
      run: dotnet test /ef-examples/source/ef-examples.csproj --no-build --verbosity normal
      
    - name: Qodana - Code Inspection
      uses: JetBrains/qodana-action@v2.0-eap
      with: 
        results-dir: "/build-agent/qudana/results"
        cache-dir:  "/build-agent/qudana/cache"
